version: '3'

services:
  # Container do banco de dados
  database:
    image: mysql:5.7
    container_name: mysql_compose
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: orm_example
      MYSQL_HOST: database
    volumes:
      - ./backend:/docker-entrypoint-initdb.d

  # Container da API (backend)
  api:
    image: node:14
    container_name: backend
    tty: true
    stdin_open: true
    command: npm run dev
    restart: always
    ports:
      - 3333:3333
    depends_on:
      - database
    working_dir: /app
    volumes:
      - ./backend:/app
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: orm_example
      MYSQL_HOST: database
      MYSQL_PORT: 3306

  # Container da aplicação web (frontend)
  web:
    image: node:14
    container_name: frontend
    tty: true
    stdin_open: true
    command: npm start
    ports:
      - 3000:3000
    depends_on:
      - api
    working_dir: /app
    volumes:
      - ./frontend:/app
